### ISSUE TITLE
what is the difference than text-generation-webui

### ISSUE THREAD

**Issue by panpan0000** [InftyAI/llmaz-dashboard#20]
aka: target comparison with https://github.com/oobabooga/text-generation-webui

**Comment by kerthcet** [comment]
Took a glance of the text-generation-webui, it's a great project but seems more dedicated to model serving, what llmaz hopes to solve including both the serving and fine tuning, prompt management and other stuff around LLMs. And llmaz is building on top of kubernetes, that's the biggest difference I think.
