### ISSUE TITLE
Idea: is it possible to make it k8s-CRD?

### ISSUE THREAD

**Issue by panpan0000** [InftyAI/llmaz-dashboard#21]
example: 
user: create a CRD to serve xx model with parameter yyy.
Llmaz: than it will be there.

in another word, using CRD to be "API" for Llmaz,  together with graio as "UX" for Llmaz.

**Comment by kerthcet** [comment]
Thanks for the input, that's what https://github.com/InftyAI/llmaz-operator aims to do, we'll support 
- CRD
- python library
- Web UI
as we projected. But that's a long-term plan.
